### PR TITLE
Opengl android: Fix build on Android

### PR DESCRIPTION
**Pull request by leamas**
This builds on all platforms. I note that there are lot's of thing commented out, so I guess it doesn't really work. Bit, it builds, and that is a starter.

The basic steps:
 - Drop glshim (not useful on Android)
 - Update AndroidHeaders to current shipdriver state which includes GLES and GLES2
 - Restore various hacks in CMakeLists aimed include GL in different ways; drop corresponding headers.
 - Change inclusion order to avoid gl.h being included before gl2.h whcih creates conflicts.
 - Change include path on MacOS so the system header can be found.
 
+ one or two bugfixes.

### CODE REVIEW

**Comment by leamas** [comment]
Oops... forgot windows. Back to the drawing board.

**Comment by Rasbats** [comment]
This has a lot of potential for getting drawing stuff working on Android versions of plugins.
Drawing factory is just a way of setting up a class for drawing a line on the OpenCPN canvas using a new viewport.
I will continue using this plugin as a sandpit for "Hello World of Drawing" type stuff.

**Comment by leamas** [comment]
OK, but please note that build-wise there is really nothing special with oplaydo2, it's just a standard shipdriver setup. All changes are encapsulated in AndroidHeaders and  WindowsHeaders and backported to the SD templates.

That said, the actual code need to include the headers in the correct way, but that is another issue.

**Comment by leamas** [comment]
Partly, note to /me:

The OpenGL headers are special in the way that a file like _gl.h_ in reality is platform-dependent. Using for example the Android gl.h on windows will compile, but carries all sorts of risks in runtime. That is the reason I have tried to take some care that each platform (Windows, flatpak, Linux, MacOS, Android) is using it's own set of opengl header files.

**Pull request merged**
